### ISSUE TITLE
it works bad for tag <h*>

### ISSUE THREAD

**Issue by kevin1211** [abusaidm/html-snippets#10]
when i code tag such as `h1` , and type <tab>, it will show me `<h1></h1>` what  troubled me is that the cursor in a wrong place (between "/" and "h")

![qq20160912-0](https://cloud.githubusercontent.com/assets/13352521/18433561/ddab1a04-791a-11e6-9ab7-4f6cfd7cd694.png)

**Comment by abusaidm** [comment]
Hello I have looked into this I have applied a fix for this, please update to 0.0.16 and this should resolve the issue for you.

**Comment by kevin1211** [comment]
it works perfectly, thanks for you very much.
