### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by iwozzy** [abusaidm/html-snippets#11]
Is there a complete documentation of how it works somewhere?

I found out by chance that `script:src` will expand to `<script src=""></script>` and found that very useful! I wonder what else can be done and how but I can't find the documentation.

Great extension!

**Comment by Emeryao** [comment]
I think that's the magic of zen coding cause you can still use `script:src` without this extension installed 😆

**Comment by abusaidm** [comment]
that feature is actually a new feature added by vs code html engine not my extension. sorry to disappoint.
you can read the snippets file for the list of code this extension supports.

thank you

**Comment by iwozzy** [comment]
Not disappointing at all! Thank you for this extension! I'll have a look in the snippets file.
