### ISSUE TITLE
html-snippets in php file

### ISSUE THREAD

**Issue by dzung1nguyen** [abusaidm/html-snippets#12]
Hi Guys,

Pls help me config it to use in php file

Thanks

**Comment by jleifeld** [comment]
I create a pull request for the php support. This should fix the problem.

**Comment by abusaidm** [comment]
the pull has been merged and the changed pushed to version 0.0.17 sorry for delay been busy with other work.

thank you

**Comment by dzung1nguyen** [comment]
Thank you so much!
