### ISSUE TITLE
Since VSCode vs 1.6.0 - snippet options not being chosen by default when hitting the tab key

### ISSUE THREAD

**Issue by BrandonRice** [abusaidm/html-snippets#16]
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: abusaidm.html-snippets-0.0.17, anseki.vscode-color-0.1.11, asp, bradgashler.htmltagwrap-0.0.3, ecmel.vscode-html-css-0.0.28, eg2.vscode-npm-script-0.0.20, fabianlauer.vs-code-xml-format-0.1.2, HookyQR.beautify-0.4.0, MattiasPernhult.vscode-todo-0.8.0, ms-vscode.Theme-3024Kit-0.1.1, msjsdiag.debugger-for-chrome-1.1.0, robertohuertasm.vscode-icons-3.0.4, seanmcbreen.Spell-0.8.6, tron.asp-0.0.1, wcwhitehead.bootstrap-3-snippets-0.0.7, xabikos.JavaScriptSnippets-1.2.0, Zignd.html-css-class-completion-1.0.3

Steps to reproduce:

1.  Type any tag
2.  When the snippet selector comes up, the correct auto-complete snippet would be at the top of the list but now I have to hit the up arrow on my keypad to get it to work correctly.

Demonstration video:

![2016-10-13_09-45-50](https://cloud.githubusercontent.com/assets/6462859/19353733/f21cac60-9129-11e6-9b0e-db8d7eafea30.gif)

**Comment by cottrellio** [comment]
I just fixed this by sorting the snippets to appear at the top of the suggestions menu. I don't know if you're having the same problem I was, but it's worth a try.

Try adding `"editor.snippetSuggestions": "top",` to your settings.

**Comment by BrandonRice** [comment]
Yes!  This worked for me!  Thank you @cottrellio !!

**Comment by abusaidm** [comment]
Hello @BrandonRice 
this is a late reply, since you got this resolved by @cottrellio , I will close this issue. I can't do much in the snippet code because vscode takes snippets as secondary priority by default, the solution @cottrellio  provided is the most accurate one to my knowledge.

Thank you @BrandonRice for the report and thank you @cottrellio for providing the quick solution.
