### ISSUE TITLE
Remove snippet support in <style> tag

### ISSUE THREAD

**Issue by Reedo0910** [abusaidm/html-snippets#17]
CSS code completion has returned in VSCode 1.7.1,but html snippet still works in <style> tag, and it's being chosen by default.
![htmlsnippet](https://cloud.githubusercontent.com/assets/19267441/20000804/4fd0e0f6-a2b4-11e6-93fb-df0ee8bbdf4f.PNG)

**Comment by abusaidm** [comment]
Hello,

can you check to see what the "editor.snippetSuggestions" value is in your user settings?
try to put it to "bottom".

I haven't seen this one before so will need to investigate this issue further.

**Comment by Reedo0910** [comment]
That's weird. I didn't change the "editor.snippetSuggestions" value, it is "bottom" by default.

**Comment by abusaidm** [comment]
vs code seems to have improved its intelisense algorithm for finding the best match.
example:

"col" is only 3 letters and its a snippet you enabled for HTML, when you type co the engine is showing you the most relevant and that will be "col" followed by "color" ...  as "col" is closer to "co" than "color" in the number of letters. And this only shows to things that are similar in snippet and the css.

let me know if that cleared things up.

**Comment by Reedo0910** [comment]
Yes, that's what the new vscode has shown me.

**Comment by abusaidm** [comment]
I think we will see what the vscode team will say about this, if its the way going forward or if this is a bug in the algorithm.

**Comment by Reedo0910** [comment]
OK. Thanks for your reply.
