### ISSUE TITLE
Keywords in comments are expanded to tags

### ISSUE THREAD

**Issue by jamisonbryant** [abusaidm/html-snippets#22]
Example: Typing the following comment

`// Add columns to table`

and pressing ENTER gives:

```
// Add columns to <table>

</table>
```

Suggestion: configure extension to ignore keywords in `//` and `/* */` comment blocks.

**Comment by abusaidm** [comment]
Hello, sorry about late reply,

I cannot actually control this, this is controlled by VSCode engine its self.

Thank you
