### ISSUE TITLE
Snippets works in wrong places

### ISSUE THREAD

**Issue by dehghani-mehdi** [abusaidm/html-snippets#23]
Hi,
Thank you for this extension, but (for ex.) in __JS file__ when I'm typing `selec`, the html snippets shown up and if I hit tab, `<select></select>` will be inserted.
It's very painful and I had to disable your extension.

Please fix this issue :)

**Comment by Robertb4** [comment]
This happens to me too. The html snippets show up in JS files as well which is very annoying. I will disable them if I can't fix this

**Comment by abusaidm** [comment]
hello @dehghani-mehdi 
I have resolved this now, sorry about delay.
