### ISSUE TITLE
Some of my doubts

### ISSUE THREAD

**Issue by humuye** [abusaidm/html-snippets#32]
Examples：
When I press the tab key
![daima](https://cloud.githubusercontent.com/assets/22143654/25267402/3635c428-26a7-11e7-8bda-948ecb3c2c4a.gif)
But I want it to appear with the following code，press the tab key
![2](https://cloud.githubusercontent.com/assets/22143654/25267945/73236b90-26a9-11e7-8cf2-79472c228cb1.jpg)

thank you

**Comment by abusaidm** [comment]
hello, 

this extension was never design for expanding multi blocks, its a snippet extension.

**Comment by humuye** [comment]
Thank you. Vscode staff has helped me solve this problem.
https://github.com/Microsoft/vscode/issues/1952#issuecomment-257811974

**Comment by abusaidm** [comment]
thanks for showing me the comment, thats actually really helpful

Thanks
