### ISSUE TITLE
Tag completion doesn't work when using multiple cursors

### ISSUE THREAD

**Issue by TechMky** [abusaidm/html-snippets#33]
Hey @abusaidm ,
I really like your extension and to be honest, you have done a better work than Microsoft. 

I'm not sure if this was intended or not but still would like to know about this issue.
VS Code: 1.11
Extension: 0.1.0
notice the completion of "td"
![](http://g.recordit.co/9CYHmipDOe.gif)

**Comment by abusaidm** [comment]
hi @TechMky ,

Thanks, this does seem like a bug, I have just tested a similar code to yours on the following spec and all worked normal:
VS Code 1.11.2
Extension 0.1.0
OS: OSX 10.12.2

can you try upgrade your vscode and see what you get.

**Comment by TechMky** [comment]
Hi @abusaidm ,

I've just updated my VS Code to 1.11.2 but the issue still remains.

**Comment by abusaidm** [comment]
Hi,

can i suggest you try the extension without any other extensions active, to see if another extension is interfering

**Comment by TechMky** [comment]
Hey there,

I tried as you said, still no luck. Can you just show me how it's working on your side? like in gif or something?

**Comment by abusaidm** [comment]
Hello

I tried to do like your gif showed.
![](https://media.giphy.com/media/l1BgT4vtZJaNgZ6c8/giphy.gif)

**Comment by abusaidm** [comment]
Hey @TechMky 

sorry I miss understood your question, sorry I just reread the thread now.
If am correct the issue you are having is to do with applying a snippet on multiple cursor positions.

that is a VSCode issue and its already reported: [VSCode github](https://github.com/Microsoft/vscode/issues/16037)

**Comment by TechMky** [comment]
Hi @abusaidm 

Alright man, Thanks.
