### ISSUE TITLE
can't work well

### ISSUE THREAD

**Issue by chwentao** [abusaidm/html-snippets#4]
when input a tag ,after input enter, not autocomplete.

**Comment by nCubed** [comment]
I agree the auto-complete is not intuitive where the closing tag is not added when the opening tag is manually closed.

`<SomeTag>` --> tab / enter --> no closing tag

However, the extension appears to expect the opening tag to not be competed:

`<SomeTag` --> tab --> opening tag completed and closing tag added.

**Comment by abusaidm** [comment]
I understand what you mean, but this is a snippet extension and I can not include this feature.
I will attempt to develop this extension as a complete html auto complete extension when I have the chance.

**Comment by chwentao** [comment]
thanks everyone. I already know how to use the and before the cause of the failure, for example, input a tag 'html' after, input enter can complete <html> </html>,but before I input the <html>  after input enter. sorry ,my English is very poor.

**Comment by abusaidm** [comment]
Hello,
Sorry I did not understand what you mean.
Can you provide a example as to what you mean.

**Comment by chwentao** [comment]
I mean, I had to use it is wrong, and now know how to properly use.
