### ISSUE TITLE
HTML autocomplete LI tag does not insert a newline on enter

### ISSUE THREAD

**Issue by ayyash** [abusaidm/html-snippets#7]
- VSCode Version: 1.4.0-Insider
- OS Version: Windows 10

1. Type LI then tab (this will produce `<li></li>`)
2. Type enter (to make a new line between the `<li></li>`)

Expected: a new line insert between the tags
Buggy behavior: The cursor jumps outside of the LI tags

**Comment by abusaidm** [comment]
thanks, I will look into it and fix the issue this week hopefully.

**Comment by abusaidm** [comment]
Hello ayyash, I have fixed the issue in version 0.0.14.
thanks for reporting it.

**Comment by ayyash** [comment]
awesome, thanks
