### ISSUE TITLE
Does this work with php files?

### ISSUE THREAD

**Issue by n2fole00** [abusaidm/html-snippets#9]
Hi, I was wondering if this extension was meant to work with php files? I can get the completion popup to appear in html files, but cannot get it to work in php files (outside of php tags of course). 

Thanks. 

**HTML-Snippets version:** 0.0.14

**Visual Studio Code Info:**
Version 1.4.0
Commit 6276dcb0ae497766056b4c09ea75be1d76a8b679
Date 2016-08-04T16:49:32.489Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

**Comment by abusaidm** [comment]
hello,
in its current format this only works in .html files or files vs code recognises as html, if you change the lang in the right bottom corner to html this will do it, but i will try work away to allow otherwise, sorry currently working on other projects.
